# Config file for an example Majora's Mask: Recompiled mod.

# Fields that end up in the mod's manifest.
[manifest]

# Unique ID of this mod. Pick something long enough that it'll never be the same as any other mod.
# The name displayed in the mod management menu is separate from this so this doesn't need to be human readable.
id = "input_displayer"

# Version of this mod.
version = "0.0.0"

# The name that will show up for this mod in the mod menu. This should be human readable.
display_name = "InputDisplay"

# The description that will show up when this mod is displayed in the mod menu. This should be human readable.
description =  """InputDisplay For MM Recomp.
Still in developement. Done with the amazing help of the community."""

# A short description that will show up in this mod's entry in the mod list. This should be human readable and kept short
# to prevent it from being cut off due to the limited space.
short_description = "InputDipslay"

# Authors of this mod.
authors = [ "Eppe" ]

# ID of the target recomp game.
game_id = "mm"

# Minimum version of the target recomp (e.g. Zelda 64: Recompiled) that this mod can run on.
minimum_recomp_version = "1.2.0"

# Dependency mods. Each entry is the mod's ID and then an optional minimum version of the dependency mod.
dependencies = [
# Example dependency:
#    "modname:1.0.0"
]

# Native libraries (e.g. DLLs) and the functions they export.
native_libraries = [
# Example native library:
#    { name = "my_native_library", funcs = ["my_native_library_function"] }
]

# Inputs to the mod tool.
[inputs]

# Input elf file to generate a mod from.
elf_path = "build/mod.elf"

# Output mod filename.
mod_filename = "InputDisplay_Dev"

# Reference symbol files.
func_reference_syms_file = "Zelda64RecompSyms/mm.us.rev1.syms.toml"
data_reference_syms_files = [ "Zelda64RecompSyms/mm.us.rev1.datasyms.toml", "Zelda64RecompSyms/mm.us.rev1.datasyms_static.toml" ]

# Additional files to include in the mod.
additional_files = [ ]
# Config options.

[[manifest.config_options]]
id = "input_display_deadzone"
name = "Deadzone Viewer"
description = """Makes the input viewer show the Deadzone.
Off makes the input viewer not show the Deadzone on the
analog.
On makes the input viewer show the Deadzone of the analog
"""
type = "Enum"
options = [
    "Off",
    "On",
]
default = "Off"

[[manifest.config_options]]
id = "button_placement_option"
name = "L Button"
description = """Add the L Button.
"""
type = "Enum"
options = [
    "Off",
    "On",
]
default = "Off"

[[manifest.config_options]]
id = "overlay_placement_option"
name = "L Button"
description = """Change overlay placement.
"""
type = "Enum"
options = [
    "Left",
    "Center",
    "Right",
]
default = "Left"


[[manifest.config_options]]
id = "pos_y_display"
name = "Position Y InputViewer"
description = "Test number config option."
type = "Number"
min = -58
max = 145
step = 1
precision = 1
percent = false
default = 100
