# Config file for an example Majora's Mask: Recompiled mod.

# Fields that end up in the mod's manifest.
[manifest]

# Unique ID of this mod. Pick something long enough that it'll never be the same as any other mod.
# The name displayed in the mod management menu is separate from this so this doesn't need to be human readable.
id = "mm_recomp_input_viewer"

# Version of this mod.
version = "1.0.0"

# The name that will show up for this mod in the mod menu. This should be human readable.
display_name = "Input Viewer"

# The description that will show up when this mod is displayed in the mod menu. This should be human readable.
description =  """A mod that allows you to view the input pressed on the screen in real time.

A huge thanks to Wombat, danielryb and a lot of other members of the recomp community for their help.
<3
"""

# A short description that will show up in this mod's entry in the mod list. This should be human readable and kept short
# to prevent it from being cut off due to the limited space.
short_description = "A mod that shows the input pressed."

# Authors of this mod.
authors = [ "Eppe" ]

# ID of the target recomp game.
game_id = "mm"

# Minimum version of the target recomp (e.g. Zelda 64: Recompiled) that this mod can run on.
minimum_recomp_version = "1.2.0"

# Dependency mods. Each entry is the mod's ID and then an optional minimum version of the dependency mod.
dependencies = [
# Example dependency:
#    "modname:1.0.0"
]

# Native libraries (e.g. DLLs) and the functions they export.
native_libraries = [
# Example native library:
#    { name = "my_native_library", funcs = ["my_native_library_function"] }
]

# Inputs to the mod tool.
[inputs]

# Input elf file to generate a mod from.
elf_path = "build/mod.elf"

# Output mod filename.
mod_filename = "mm_Input_Viewer"

# Reference symbol files.
func_reference_syms_file = "Zelda64RecompSyms/mm.us.rev1.syms.toml"
data_reference_syms_files = [ "Zelda64RecompSyms/mm.us.rev1.datasyms.toml", "Zelda64RecompSyms/mm.us.rev1.datasyms_static.toml" ]

# Additional files to include in the mod.
additional_files = ["thumb.png"]
# Config options.

[[manifest.config_options]]
id = "controller_layout_option"
name = "Overlay Layout"
description = """ Change the overlay of the input viewer.
N64: Use the N64 controller layout.
GCN: Use the GCN controller layout
Note: The L Button is mapped on the DPad Down on the gamecube controller
so if you press L, it will appear as pressed on Dpad Down.
"""
type = "Enum"
options = [
    "N64",
    "GCN",
]
default = "N64"

[[manifest.config_options]]
id = "button_placement_option"
name = "Show L Button"
description = """Add or remove the L Button from the input viewer.
Note: Setting the option to Off makes the Right trigger to the R Button
while the left button will be the Z button instead of the L Button
"""
type = "Enum"
options = [
    "Off",
    "On",
]
default = "On"

[[manifest.config_options]]
id = "input_display_deadzone"
name = "Extended Superslide Viewer"
description = """Makes the input viewer distinctly show the ESS zone. (Useful for HESS)
Off makes the input viewer not show the dead zone or the ESS zone of the analog.
On makes the input viewer show the Deadzone and ESS zone of the analog:
    Black: No input will be registered
    Green: ESS Zone
    Red: Outside of the ESS Zone
"""
type = "Enum"
options = [
    "Off",
    "On",
]
default = "Off"

[[manifest.config_options]]
id = "overlay_placement_option"
name = "Overlay Placement"
description = """Change the position of the input viewer.
Note #1: If you select either option, please change the value of
the X-Axis to see the input viewer again.
Note #2: If you select Left, the input viewer will be cut if it is on the right
And vice versa if you select Right.
"""
type = "Enum"
options = [
    "Left",
    "Right",
]
default = "Left"


[[manifest.config_options]]
id = "pos_y_display"
name = "Overlay Y Axis position"
description = "Change the value of the Y axis of the input viewer."
type = "Number"
min = -58
max = 145
step = 1
precision = 1
percent = false
default = 100

[[manifest.config_options]]
id = "pos_x_display"
name = "Overlay X Axis position"
description = "Change the value of the X axis of the input viewer."
type = "Number"
min = -50
max = 300
step = 1
precision = 1
percent = false
default = 145

[[manifest.config_options]]
id = "custom_color_option"
name = "Custom Button Color"
description = """Setting that allows to change the color of each buttons.

Credit to Neirn for her code to convert a string to a hex value (You're amazing!)
"""
type = "Enum"
options = [
    "Normal",
    "Custom",
]
default = "Normal"

[[manifest.config_options]]
id = "stick_color"
name = "Analog Color"
description = "Hex color value of the analog.\nPlease select 'Custom' in 'Custom Button Color' if you want to change the color of each button.\n\nDefault: FFFFFF\n\n\nNote: If the ESS Viewer is activated, you won't be able to change the color of the stick."
type = "String"
default = "FFFFFF"

[[manifest.config_options]]
id = "trigger_color"
name = "Triggers Color"
description = "Hex color value of the analog.\nPlease select 'Custom' in 'Custom Button Color' if you want to change the color of each button.\n\nDefault: FFFFFF"
type = "String"
default = "FFFFFF"

[[manifest.config_options]]
id = "a_button_color"
name = "A Button Color"
description = "Hex color value of the analog.\nPlease select 'Custom' in 'Custom Button Color' if you want to change the color of each button.\n\nDefault: 0000FF"
type = "String"
default = "0000FF"

[[manifest.config_options]]
id = "b_button_color"
name = "B Button Color"
description = "Hex color value of the analog.\nPlease select 'Custom' in 'Custom Button Color' if you want to change the color of each button.\n\nDefault: 00FF00"
type = "String"
default = "00FF00"

[[manifest.config_options]]
id = "start_button_color"
name = "Start Button Color"
description = "Hex color value of the analog.\nPlease select 'Custom' in 'Custom Button Color' if you want to change the color of each button.\n\nDefault: FF0000"
type = "String"
default = "FF0000"

[[manifest.config_options]]
id = "dpad_color"
name = "D-Pad Color"
description = "Hex color value of the analog.\nPlease select 'Custom' in 'Custom Button Color' if you want to change the color of each button.\n\nDefault: 808080"
type = "String"
default = "808080"

[[manifest.config_options]]
id = "c_button_color"
name = "C-Buttons Color"
description = "Hex color value of the analog.\nPlease select 'Custom' in 'Custom Button Color' if you want to change the color of each button.\n\nDefault: FFFF00"
type = "String"
default = "FFFF00"

[[manifest.config_options]]
id = "x_button_color_gcn"
name = "X Button Color (GCN)"
description = "Hex color value of the analog.\nPlease select 'Custom' in 'Custom Button Color' if you want to change the color of each button.\n\nDefault: FFFFFF"
type = "String"
default = "FFFFFF"

[[manifest.config_options]]
id = "y_button_color_gcn"
name = "Y Button Color (GCN)"
description = "Hex color value of the analog.\nPlease select 'Custom' in 'Custom Button Color' if you want to change the color of each button.\n\nDefault: FFFFFF"
type = "String"
default = "FFFFFF"

[[manifest.config_options]]
id = "z_button_color_gcn"
name = "Z Button Color (GCN)"
description = "Hex color value of the analog.\nPlease select 'Custom' in 'Custom Button Color' if you want to change the color of each button.\n\nDefault: A020F0"
type = "String"
default = "A020F0"

[[manifest.config_options]]
id = "c_stick_color_gcn"
name = "C-Stick Color (GCN)"
description = "Hex color value of the analog.\nPlease select 'Custom' in 'Custom Button Color' if you want to change the color of each button.\n\nDefault: FFFF00"
type = "String"
default = "FFFF00"